# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: centos-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: Terraform INIT
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'xxxxxxxxxx'
    backendAzureRmResourceGroupName: 'rg-mediawiki'
    backendAzureRmStorageAccountName: 'sa-mediawiki'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'xxxxxxxxxx'

- task: TerraformTaskV4@4
  displayName: Terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'xxxxxxxx'


